name: deula
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  circular_indicator: ^1.0.6
  easy_localization: ^3.0.7+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  go_router: ^15.1.3
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
